version: "3"

services:
  backend:
    env_file:
      - .env
    networks:
      - default
    ports:
      - 8000:$API_PORT
    build:
      context: ./backend
      dockerfile: Dockerfile
networks:
  default:
