name: Lint Backend

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "backend/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install dependencies
        working-directory: ${{ env.working-directory }}
        run: poetry install

      - name: Run Lint
        uses: chartboost/ruff-action@v1
        with:
          src: ${{ env.working-directory }}
